controller_manager:
  ros__parameters:
    update_rate: 100

    actuator_position_controller:
      type: position_controllers/JointGroupPositionController

actuator_position_controller:
  ros__parameters:
    joints:
      - actuator_extension_joint
